/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-04-05 03:14:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.console.base;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AMAdminFrame_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  public java.lang.String getServletInfo() {
    return "AMAdminFrame";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jato.tld", Long.valueOf(1493219492000L));
    _jspx_dependants.put("/WEB-INF/com_sun_web_ui/cc.tld", Long.valueOf(1493219494000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005fclassName;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005fi18nbundle_0026_005flocale_005fid_005fbaseName_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjato_005ftext_0026_005fname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005fclassName = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005fi18nbundle_0026_005flocale_005fid_005fbaseName_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fjato_005ftext_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005fclassName.release();
    _005fjspx_005ftagPool_005fcc_005fi18nbundle_0026_005flocale_005fid_005fbaseName_005fnobody.release();
    _005fjspx_005ftagPool_005fjato_005ftext_0026_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      //  jato:useViewBean
      com.iplanet.jato.taglib.UseViewBeanTag _jspx_th_jato_005fuseViewBean_005f0 = (com.iplanet.jato.taglib.UseViewBeanTag) _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005fclassName.get(com.iplanet.jato.taglib.UseViewBeanTag.class);
      boolean _jspx_th_jato_005fuseViewBean_005f0_reused = false;
      try {
        _jspx_th_jato_005fuseViewBean_005f0.setPageContext(_jspx_page_context);
        _jspx_th_jato_005fuseViewBean_005f0.setParent(null);
        // /console/base/AMAdminFrame.jsp(37,0) name = className type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_jato_005fuseViewBean_005f0.setClassName("com.sun.identity.console.base.AMAdminFrameViewBean");
        int _jspx_eval_jato_005fuseViewBean_005f0 = _jspx_th_jato_005fuseViewBean_005f0.doStartTag();
        if (_jspx_eval_jato_005fuseViewBean_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          com.iplanet.jato.view.ContainerView currentContainerView = null;
          com.iplanet.jato.view.TiledView currentTiledView = null;
          com.iplanet.jato.view.TreeView currentTreeView = null;
          com.sun.identity.console.base.AMAdminFrameViewBean viewBean = null;
          currentContainerView = (com.iplanet.jato.view.ContainerView) _jspx_page_context.findAttribute("currentContainerView");
          currentTiledView = (com.iplanet.jato.view.TiledView) _jspx_page_context.findAttribute("currentTiledView");
          currentTreeView = (com.iplanet.jato.view.TreeView) _jspx_page_context.findAttribute("currentTreeView");
          viewBean = (com.sun.identity.console.base.AMAdminFrameViewBean) _jspx_page_context.findAttribute("viewBean");
          do {
            out.write('\n');
            out.write('\n');
            //  cc:i18nbundle
            com.sun.web.ui.taglib.i18n.CCBundleTag _jspx_th_cc_005fi18nbundle_005f0 = (com.sun.web.ui.taglib.i18n.CCBundleTag) _005fjspx_005ftagPool_005fcc_005fi18nbundle_0026_005flocale_005fid_005fbaseName_005fnobody.get(com.sun.web.ui.taglib.i18n.CCBundleTag.class);
            boolean _jspx_th_cc_005fi18nbundle_005f0_reused = false;
            try {
              _jspx_th_cc_005fi18nbundle_005f0.setPageContext(_jspx_page_context);
              _jspx_th_cc_005fi18nbundle_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jato_005fuseViewBean_005f0);
              // /console/base/AMAdminFrame.jsp(39,0) name = baseName type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_cc_005fi18nbundle_005f0.setBaseName("amConsole");
              // /console/base/AMAdminFrame.jsp(39,0) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_cc_005fi18nbundle_005f0.setId("amConsole");
              // /console/base/AMAdminFrame.jsp(39,0) name = locale type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_cc_005fi18nbundle_005f0.setLocale(((com.sun.identity.console.base.AMViewBeanBase)viewBean).getUserLocale());
              int _jspx_eval_cc_005fi18nbundle_005f0 = _jspx_th_cc_005fi18nbundle_005f0.doStartTag();
              if (_jspx_th_cc_005fi18nbundle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fcc_005fi18nbundle_0026_005flocale_005fid_005fbaseName_005fnobody.reuse(_jspx_th_cc_005fi18nbundle_005f0);
              _jspx_th_cc_005fi18nbundle_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005fi18nbundle_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005fi18nbundle_005f0_reused);
            }
            out.write(" \n");
            out.write("\n");
            out.write("<head>\n");
            out.write("<script language=\"javascript\">\n");
            out.write("    top.location.replace(\"");
            if (_jspx_meth_jato_005ftext_005f0(_jspx_th_jato_005fuseViewBean_005f0, _jspx_page_context))
              return;
            out.write("\");\n");
            out.write("</script>\n");
            out.write("</head>\n");
            out.write("<body></body>\n");
            int evalDoAfterBody = _jspx_th_jato_005fuseViewBean_005f0.doAfterBody();
            currentContainerView = (com.iplanet.jato.view.ContainerView) _jspx_page_context.findAttribute("currentContainerView");
            currentTiledView = (com.iplanet.jato.view.TiledView) _jspx_page_context.findAttribute("currentTiledView");
            currentTreeView = (com.iplanet.jato.view.TreeView) _jspx_page_context.findAttribute("currentTreeView");
            viewBean = (com.sun.identity.console.base.AMAdminFrameViewBean) _jspx_page_context.findAttribute("viewBean");
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_jato_005fuseViewBean_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005fclassName.reuse(_jspx_th_jato_005fuseViewBean_005f0);
        _jspx_th_jato_005fuseViewBean_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_jato_005fuseViewBean_005f0, _jsp_getInstanceManager(), _jspx_th_jato_005fuseViewBean_005f0_reused);
      }
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_jato_005ftext_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_jato_005fuseViewBean_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jato:text
    com.iplanet.jato.taglib.html.StaticTextFieldTag _jspx_th_jato_005ftext_005f0 = (com.iplanet.jato.taglib.html.StaticTextFieldTag) _005fjspx_005ftagPool_005fjato_005ftext_0026_005fname_005fnobody.get(com.iplanet.jato.taglib.html.StaticTextFieldTag.class);
    boolean _jspx_th_jato_005ftext_005f0_reused = false;
    try {
      _jspx_th_jato_005ftext_005f0.setPageContext(_jspx_page_context);
      _jspx_th_jato_005ftext_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jato_005fuseViewBean_005f0);
      // /console/base/AMAdminFrame.jsp(44,26) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_jato_005ftext_005f0.setName("txtViewbeanURL");
      int _jspx_eval_jato_005ftext_005f0 = _jspx_th_jato_005ftext_005f0.doStartTag();
      if (_jspx_th_jato_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fjato_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_jato_005ftext_005f0);
      _jspx_th_jato_005ftext_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_jato_005ftext_005f0, _jsp_getInstanceManager(), _jspx_th_jato_005ftext_005f0_reused);
    }
    return false;
  }
}
