/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-04-11 04:49:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.config.auth.default_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Logout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  public java.lang.String getServletInfo() {
    return "Logout";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jato.tld", Long.valueOf(1493219492000L));
    _jspx_dependants.put("/WEB-INF/auth.tld", Long.valueOf(1493219492000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005fclassName;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjato_005ftext_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjato_005fcontent_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fauth_005fhref_0026_005fname_005ffireDisplayEvents;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fauth_005fresBundle_0026_005fresourceKey_005fbundleName_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005fclassName = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fjato_005ftext_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fjato_005fcontent_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fauth_005fhref_0026_005fname_005ffireDisplayEvents = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fauth_005fresBundle_0026_005fresourceKey_005fbundleName_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005fclassName.release();
    _005fjspx_005ftagPool_005fjato_005ftext_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fjato_005fcontent_0026_005fname.release();
    _005fjspx_005ftagPool_005fauth_005fhref_0026_005fname_005ffireDisplayEvents.release();
    _005fjspx_005ftagPool_005fauth_005fresBundle_0026_005fresourceKey_005fbundleName_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    ");
      //  jato:useViewBean
      com.iplanet.jato.taglib.UseViewBeanTag _jspx_th_jato_005fuseViewBean_005f0 = (com.iplanet.jato.taglib.UseViewBeanTag) _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005fclassName.get(com.iplanet.jato.taglib.UseViewBeanTag.class);
      boolean _jspx_th_jato_005fuseViewBean_005f0_reused = false;
      try {
        _jspx_th_jato_005fuseViewBean_005f0.setPageContext(_jspx_page_context);
        _jspx_th_jato_005fuseViewBean_005f0.setParent(null);
        // /config/auth/default/Logout.jsp(37,4) name = className type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_jato_005fuseViewBean_005f0.setClassName("com.sun.identity.authentication.UI.LogoutViewBean");
        int _jspx_eval_jato_005fuseViewBean_005f0 = _jspx_th_jato_005fuseViewBean_005f0.doStartTag();
        if (_jspx_eval_jato_005fuseViewBean_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          com.iplanet.jato.view.ContainerView currentContainerView = null;
          com.iplanet.jato.view.TiledView currentTiledView = null;
          com.iplanet.jato.view.TreeView currentTreeView = null;
          com.sun.identity.authentication.UI.LogoutViewBean viewBean = null;
          currentContainerView = (com.iplanet.jato.view.ContainerView) _jspx_page_context.findAttribute("currentContainerView");
          currentTiledView = (com.iplanet.jato.view.TiledView) _jspx_page_context.findAttribute("currentTiledView");
          currentTreeView = (com.iplanet.jato.view.TreeView) _jspx_page_context.findAttribute("currentTreeView");
          viewBean = (com.sun.identity.authentication.UI.LogoutViewBean) _jspx_page_context.findAttribute("viewBean");
          do {
            out.write("\n");
            out.write("        \n");
            out.write("        <head>\n");
            out.write("            <title>");
            if (_jspx_meth_jato_005ftext_005f0(_jspx_th_jato_005fuseViewBean_005f0, _jspx_page_context))
              return;
            out.write("</title>\n");
            out.write("            ");

                String ServiceURI = (String) viewBean.getDisplayFieldValue(viewBean.SERVICE_URI);
            
            out.write("\n");
            out.write("            <link href=\"");
            out.print( ServiceURI);
            out.write("/css/new_style.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
            out.write("            <!--[if IE 9]> <link href=\"");
            out.print( ServiceURI );
            out.write("/css/ie9.css\" rel=\"stylesheet\" type=\"text/css\"> <![endif]-->\n");
            out.write("            <!--[if lte IE 7]> <link href=\"");
            out.print( ServiceURI );
            out.write("/css/ie7.css\" rel=\"stylesheet\" type=\"text/css\"> <![endif]-->\n");
            out.write("        </head>\n");
            out.write("        <body>\n");
            out.write("            <div class=\"container_12\">\n");
            out.write("                <div class=\"grid_4 suffix_8\">\n");
            out.write("                    <a class=\"logo\" href=\"");
            out.print( ServiceURI);
            out.write("\"></a>\n");
            out.write("                </div>\n");
            out.write("                <div class=\"box box-spaced clear-float\">\n");
            out.write("                    <div class=\"grid_3\">\n");
            out.write("                        <div class=\"product-logo\"></div>\n");
            out.write("                    </div>\n");
            out.write("                    <div class=\"grid_9\">\n");
            out.write("                        <div class=\"box-content clear-float\">\n");
            out.write("                            <div class=\"message\">\n");
            out.write("                                <span class=\"icon info\"></span>\n");
            out.write("                                <h3>\n");
            out.write("                                    ");
            if (_jspx_meth_jato_005fcontent_005f0(_jspx_th_jato_005fuseViewBean_005f0, _jspx_page_context))
              return;
            out.write("\n");
            out.write("                                </h3>\n");
            out.write("                                ");
            if (_jspx_meth_jato_005fcontent_005f1(_jspx_th_jato_005fuseViewBean_005f0, _jspx_page_context))
              return;
            out.write("\n");
            out.write("                            </div>\n");
            out.write("                        </div>\n");
            out.write("                    </div>\n");
            out.write("                </div>\n");
            out.write("                <div class=\"footer alt-color\">\n");
            out.write("                    <div class=\"grid_6 suffix_3\">\n");
            out.write("                        <p>");
            if (_jspx_meth_auth_005fresBundle_005f0(_jspx_th_jato_005fuseViewBean_005f0, _jspx_page_context))
              return;
            out.write("</p>\n");
            out.write("                    </div>\n");
            out.write("                </div>\n");
            out.write("            </div>\n");
            out.write("        </body>\n");
            out.write("    ");
            int evalDoAfterBody = _jspx_th_jato_005fuseViewBean_005f0.doAfterBody();
            currentContainerView = (com.iplanet.jato.view.ContainerView) _jspx_page_context.findAttribute("currentContainerView");
            currentTiledView = (com.iplanet.jato.view.TiledView) _jspx_page_context.findAttribute("currentTiledView");
            currentTreeView = (com.iplanet.jato.view.TreeView) _jspx_page_context.findAttribute("currentTreeView");
            viewBean = (com.sun.identity.authentication.UI.LogoutViewBean) _jspx_page_context.findAttribute("viewBean");
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_jato_005fuseViewBean_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005fclassName.reuse(_jspx_th_jato_005fuseViewBean_005f0);
        _jspx_th_jato_005fuseViewBean_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_jato_005fuseViewBean_005f0, _jsp_getInstanceManager(), _jspx_th_jato_005fuseViewBean_005f0_reused);
      }
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_jato_005ftext_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_jato_005fuseViewBean_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jato:text
    com.iplanet.jato.taglib.html.StaticTextFieldTag _jspx_th_jato_005ftext_005f0 = (com.iplanet.jato.taglib.html.StaticTextFieldTag) _005fjspx_005ftagPool_005fjato_005ftext_0026_005fname_005fnobody.get(com.iplanet.jato.taglib.html.StaticTextFieldTag.class);
    boolean _jspx_th_jato_005ftext_005f0_reused = false;
    try {
      _jspx_th_jato_005ftext_005f0.setPageContext(_jspx_page_context);
      _jspx_th_jato_005ftext_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jato_005fuseViewBean_005f0);
      // /config/auth/default/Logout.jsp(40,19) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_jato_005ftext_005f0.setName("htmlTitle_Logout");
      int _jspx_eval_jato_005ftext_005f0 = _jspx_th_jato_005ftext_005f0.doStartTag();
      if (_jspx_th_jato_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fjato_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_jato_005ftext_005f0);
      _jspx_th_jato_005ftext_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_jato_005ftext_005f0, _jsp_getInstanceManager(), _jspx_th_jato_005ftext_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_jato_005fcontent_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_jato_005fuseViewBean_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jato:content
    com.iplanet.jato.taglib.ContentTag _jspx_th_jato_005fcontent_005f0 = (com.iplanet.jato.taglib.ContentTag) _005fjspx_005ftagPool_005fjato_005fcontent_0026_005fname.get(com.iplanet.jato.taglib.ContentTag.class);
    boolean _jspx_th_jato_005fcontent_005f0_reused = false;
    try {
      _jspx_th_jato_005fcontent_005f0.setPageContext(_jspx_page_context);
      _jspx_th_jato_005fcontent_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jato_005fuseViewBean_005f0);
      // /config/auth/default/Logout.jsp(62,36) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_jato_005fcontent_005f0.setName("ContentTextBoxLogout");
      int _jspx_eval_jato_005fcontent_005f0 = _jspx_th_jato_005fcontent_005f0.doStartTag();
      if (_jspx_eval_jato_005fcontent_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_jato_005fcontent_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_jato_005fcontent_005f0);
        }
        do {
          out.write("\n");
          out.write("                                        ");
          if (_jspx_meth_jato_005ftext_005f1(_jspx_th_jato_005fcontent_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_jato_005fcontent_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_jato_005fcontent_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_jato_005fcontent_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fjato_005fcontent_0026_005fname.reuse(_jspx_th_jato_005fcontent_005f0);
      _jspx_th_jato_005fcontent_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_jato_005fcontent_005f0, _jsp_getInstanceManager(), _jspx_th_jato_005fcontent_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_jato_005ftext_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_jato_005fcontent_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jato:text
    com.iplanet.jato.taglib.html.StaticTextFieldTag _jspx_th_jato_005ftext_005f1 = (com.iplanet.jato.taglib.html.StaticTextFieldTag) _005fjspx_005ftagPool_005fjato_005ftext_0026_005fname_005fnobody.get(com.iplanet.jato.taglib.html.StaticTextFieldTag.class);
    boolean _jspx_th_jato_005ftext_005f1_reused = false;
    try {
      _jspx_th_jato_005ftext_005f1.setPageContext(_jspx_page_context);
      _jspx_th_jato_005ftext_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jato_005fcontent_005f0);
      // /config/auth/default/Logout.jsp(63,40) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_jato_005ftext_005f1.setName("txtLogout");
      int _jspx_eval_jato_005ftext_005f1 = _jspx_th_jato_005ftext_005f1.doStartTag();
      if (_jspx_th_jato_005ftext_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fjato_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_jato_005ftext_005f1);
      _jspx_th_jato_005ftext_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_jato_005ftext_005f1, _jsp_getInstanceManager(), _jspx_th_jato_005ftext_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_jato_005fcontent_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_jato_005fuseViewBean_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jato:content
    com.iplanet.jato.taglib.ContentTag _jspx_th_jato_005fcontent_005f1 = (com.iplanet.jato.taglib.ContentTag) _005fjspx_005ftagPool_005fjato_005fcontent_0026_005fname.get(com.iplanet.jato.taglib.ContentTag.class);
    boolean _jspx_th_jato_005fcontent_005f1_reused = false;
    try {
      _jspx_th_jato_005fcontent_005f1.setPageContext(_jspx_page_context);
      _jspx_th_jato_005fcontent_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jato_005fuseViewBean_005f0);
      // /config/auth/default/Logout.jsp(66,32) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_jato_005fcontent_005f1.setName("ContentHrefLogout");
      int _jspx_eval_jato_005fcontent_005f1 = _jspx_th_jato_005fcontent_005f1.doStartTag();
      if (_jspx_eval_jato_005fcontent_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_jato_005fcontent_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_jato_005fcontent_005f1);
        }
        do {
          out.write("\n");
          out.write("                                    <p>\n");
          out.write("                                        ");
          if (_jspx_meth_auth_005fhref_005f0(_jspx_th_jato_005fcontent_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                                        </p>\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_jato_005fcontent_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_jato_005fcontent_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_jato_005fcontent_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fjato_005fcontent_0026_005fname.reuse(_jspx_th_jato_005fcontent_005f1);
      _jspx_th_jato_005fcontent_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_jato_005fcontent_005f1, _jsp_getInstanceManager(), _jspx_th_jato_005fcontent_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_auth_005fhref_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_jato_005fcontent_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  auth:href
    com.sun.identity.authentication.UI.taglib.DSAMEHrefTag _jspx_th_auth_005fhref_005f0 = (com.sun.identity.authentication.UI.taglib.DSAMEHrefTag) _005fjspx_005ftagPool_005fauth_005fhref_0026_005fname_005ffireDisplayEvents.get(com.sun.identity.authentication.UI.taglib.DSAMEHrefTag.class);
    boolean _jspx_th_auth_005fhref_005f0_reused = false;
    try {
      _jspx_th_auth_005fhref_005f0.setPageContext(_jspx_page_context);
      _jspx_th_auth_005fhref_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jato_005fcontent_005f1);
      // /config/auth/default/Logout.jsp(68,40) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_auth_005fhref_005f0.setName("urlLogin");
      // /config/auth/default/Logout.jsp(68,40) name = fireDisplayEvents type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_auth_005fhref_005f0.setFireDisplayEvents("true");
      int _jspx_eval_auth_005fhref_005f0 = _jspx_th_auth_005fhref_005f0.doStartTag();
      if (_jspx_eval_auth_005fhref_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_auth_005fhref_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_auth_005fhref_005f0);
        }
        do {
          if (_jspx_meth_jato_005ftext_005f2(_jspx_th_auth_005fhref_005f0, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_auth_005fhref_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_auth_005fhref_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_auth_005fhref_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fauth_005fhref_0026_005fname_005ffireDisplayEvents.reuse(_jspx_th_auth_005fhref_005f0);
      _jspx_th_auth_005fhref_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_auth_005fhref_005f0, _jsp_getInstanceManager(), _jspx_th_auth_005fhref_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_jato_005ftext_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_auth_005fhref_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jato:text
    com.iplanet.jato.taglib.html.StaticTextFieldTag _jspx_th_jato_005ftext_005f2 = (com.iplanet.jato.taglib.html.StaticTextFieldTag) _005fjspx_005ftagPool_005fjato_005ftext_0026_005fname_005fnobody.get(com.iplanet.jato.taglib.html.StaticTextFieldTag.class);
    boolean _jspx_th_jato_005ftext_005f2_reused = false;
    try {
      _jspx_th_jato_005ftext_005f2.setPageContext(_jspx_page_context);
      _jspx_th_jato_005ftext_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_auth_005fhref_005f0);
      // /config/auth/default/Logout.jsp(68,92) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_jato_005ftext_005f2.setName("txtGotoLoginAfterLogout");
      int _jspx_eval_jato_005ftext_005f2 = _jspx_th_jato_005ftext_005f2.doStartTag();
      if (_jspx_th_jato_005ftext_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fjato_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_jato_005ftext_005f2);
      _jspx_th_jato_005ftext_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_jato_005ftext_005f2, _jsp_getInstanceManager(), _jspx_th_jato_005ftext_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_auth_005fresBundle_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_jato_005fuseViewBean_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  auth:resBundle
    com.sun.identity.authentication.UI.taglib.DSAMEResBundleTag _jspx_th_auth_005fresBundle_005f0 = (com.sun.identity.authentication.UI.taglib.DSAMEResBundleTag) _005fjspx_005ftagPool_005fauth_005fresBundle_0026_005fresourceKey_005fbundleName_005fnobody.get(com.sun.identity.authentication.UI.taglib.DSAMEResBundleTag.class);
    boolean _jspx_th_auth_005fresBundle_005f0_reused = false;
    try {
      _jspx_th_auth_005fresBundle_005f0.setPageContext(_jspx_page_context);
      _jspx_th_auth_005fresBundle_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jato_005fuseViewBean_005f0);
      // /config/auth/default/Logout.jsp(77,27) name = bundleName type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_auth_005fresBundle_005f0.setBundleName("amAuthUI");
      // /config/auth/default/Logout.jsp(77,27) name = resourceKey type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_auth_005fresBundle_005f0.setResourceKey("copyright.notice");
      int _jspx_eval_auth_005fresBundle_005f0 = _jspx_th_auth_005fresBundle_005f0.doStartTag();
      if (_jspx_th_auth_005fresBundle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fauth_005fresBundle_0026_005fresourceKey_005fbundleName_005fnobody.reuse(_jspx_th_auth_005fresBundle_005f0);
      _jspx_th_auth_005fresBundle_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_auth_005fresBundle_005f0, _jsp_getInstanceManager(), _jspx_th_auth_005fresBundle_005f0_reused);
    }
    return false;
  }
}
