/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-04-05 03:15:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.console.policy;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class PolicyNormalAdd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  public java.lang.String getServletInfo() {
    return "PolicyNormalAdd";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jato.tld", Long.valueOf(1493219492000L));
    _jspx_dependants.put("/WEB-INF/com_sun_web_ui/cc.tld", Long.valueOf(1493219494000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005ffireChildDisplayEvents_005fclassName;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005fi18nbundle_0026_005flocale_005fid_005fbaseName_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005fheader_0026_005fpageTitle_005fname_005ffireDisplayEvents_005fcopyrightYear_005fbundleID;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005fform_0026_005fname_005fmethod_005fdefaultCommandChild;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fdefaultValue_005fbundleID_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005fprimarymasthead_0026_005fname_005flogoutOnClick_005fbundleID_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005fbreadcrumbs_0026_005fname_005fbundleID_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005falertinline_0026_005fname_005fbundleID_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005fpagetitle_0026_005fviewMenuLabel_005fshowPageTitleSeparator_005fshowPageButtonsTop_005fshowPageButtonsBottom_005fpageTitleText_005fpageTitleHelpMessage_005fname_005fbundleID_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcc_005fpropertysheet_0026_005fshowJumpLinks_005fname_005fbundleID_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005ffireChildDisplayEvents_005fclassName = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005fi18nbundle_0026_005flocale_005fid_005fbaseName_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005fheader_0026_005fpageTitle_005fname_005ffireDisplayEvents_005fcopyrightYear_005fbundleID = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005fform_0026_005fname_005fmethod_005fdefaultCommandChild = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fdefaultValue_005fbundleID_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005fprimarymasthead_0026_005fname_005flogoutOnClick_005fbundleID_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005fbreadcrumbs_0026_005fname_005fbundleID_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005falertinline_0026_005fname_005fbundleID_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005fpagetitle_0026_005fviewMenuLabel_005fshowPageTitleSeparator_005fshowPageButtonsTop_005fshowPageButtonsBottom_005fpageTitleText_005fpageTitleHelpMessage_005fname_005fbundleID_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcc_005fpropertysheet_0026_005fshowJumpLinks_005fname_005fbundleID_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005ffireChildDisplayEvents_005fclassName.release();
    _005fjspx_005ftagPool_005fcc_005fi18nbundle_0026_005flocale_005fid_005fbaseName_005fnobody.release();
    _005fjspx_005ftagPool_005fcc_005fheader_0026_005fpageTitle_005fname_005ffireDisplayEvents_005fcopyrightYear_005fbundleID.release();
    _005fjspx_005ftagPool_005fcc_005fform_0026_005fname_005fmethod_005fdefaultCommandChild.release();
    _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fdefaultValue_005fbundleID_005fnobody.release();
    _005fjspx_005ftagPool_005fcc_005fprimarymasthead_0026_005fname_005flogoutOnClick_005fbundleID_005fnobody.release();
    _005fjspx_005ftagPool_005fcc_005fbreadcrumbs_0026_005fname_005fbundleID_005fnobody.release();
    _005fjspx_005ftagPool_005fcc_005falertinline_0026_005fname_005fbundleID_005fnobody.release();
    _005fjspx_005ftagPool_005fcc_005fpagetitle_0026_005fviewMenuLabel_005fshowPageTitleSeparator_005fshowPageButtonsTop_005fshowPageButtonsBottom_005fpageTitleText_005fpageTitleHelpMessage_005fname_005fbundleID_005fnobody.release();
    _005fjspx_005ftagPool_005fcc_005fpropertysheet_0026_005fshowJumpLinks_005fname_005fbundleID_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      //  jato:useViewBean
      com.iplanet.jato.taglib.UseViewBeanTag _jspx_th_jato_005fuseViewBean_005f0 = (com.iplanet.jato.taglib.UseViewBeanTag) _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005ffireChildDisplayEvents_005fclassName.get(com.iplanet.jato.taglib.UseViewBeanTag.class);
      boolean _jspx_th_jato_005fuseViewBean_005f0_reused = false;
      try {
        _jspx_th_jato_005fuseViewBean_005f0.setPageContext(_jspx_page_context);
        _jspx_th_jato_005fuseViewBean_005f0.setParent(null);
        // /console/policy/PolicyNormalAdd.jsp(34,0) name = className type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_jato_005fuseViewBean_005f0.setClassName("com.sun.identity.console.policy.PolicyNormalAddViewBean");
        // /console/policy/PolicyNormalAdd.jsp(34,0) name = fireChildDisplayEvents type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_jato_005fuseViewBean_005f0.setFireChildDisplayEvents("true");
        int _jspx_eval_jato_005fuseViewBean_005f0 = _jspx_th_jato_005fuseViewBean_005f0.doStartTag();
        if (_jspx_eval_jato_005fuseViewBean_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          com.iplanet.jato.view.ContainerView currentContainerView = null;
          com.iplanet.jato.view.TiledView currentTiledView = null;
          com.iplanet.jato.view.TreeView currentTreeView = null;
          com.sun.identity.console.policy.PolicyNormalAddViewBean viewBean = null;
          currentContainerView = (com.iplanet.jato.view.ContainerView) _jspx_page_context.findAttribute("currentContainerView");
          currentTiledView = (com.iplanet.jato.view.TiledView) _jspx_page_context.findAttribute("currentTiledView");
          currentTreeView = (com.iplanet.jato.view.TreeView) _jspx_page_context.findAttribute("currentTreeView");
          viewBean = (com.sun.identity.console.policy.PolicyNormalAddViewBean) _jspx_page_context.findAttribute("viewBean");
          do {
            out.write('\n');
            out.write('\n');
            //  cc:i18nbundle
            com.sun.web.ui.taglib.i18n.CCBundleTag _jspx_th_cc_005fi18nbundle_005f0 = (com.sun.web.ui.taglib.i18n.CCBundleTag) _005fjspx_005ftagPool_005fcc_005fi18nbundle_0026_005flocale_005fid_005fbaseName_005fnobody.get(com.sun.web.ui.taglib.i18n.CCBundleTag.class);
            boolean _jspx_th_cc_005fi18nbundle_005f0_reused = false;
            try {
              _jspx_th_cc_005fi18nbundle_005f0.setPageContext(_jspx_page_context);
              _jspx_th_cc_005fi18nbundle_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jato_005fuseViewBean_005f0);
              // /console/policy/PolicyNormalAdd.jsp(38,0) name = baseName type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_cc_005fi18nbundle_005f0.setBaseName("amConsole");
              // /console/policy/PolicyNormalAdd.jsp(38,0) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_cc_005fi18nbundle_005f0.setId("amConsole");
              // /console/policy/PolicyNormalAdd.jsp(38,0) name = locale type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_cc_005fi18nbundle_005f0.setLocale(((com.sun.identity.console.base.AMViewBeanBase)viewBean).getUserLocale());
              int _jspx_eval_cc_005fi18nbundle_005f0 = _jspx_th_cc_005fi18nbundle_005f0.doStartTag();
              if (_jspx_th_cc_005fi18nbundle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fcc_005fi18nbundle_0026_005flocale_005fid_005fbaseName_005fnobody.reuse(_jspx_th_cc_005fi18nbundle_005f0);
              _jspx_th_cc_005fi18nbundle_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005fi18nbundle_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005fi18nbundle_005f0_reused);
            }
            out.write('\n');
            out.write('\n');
            if (_jspx_meth_cc_005fheader_005f0(_jspx_th_jato_005fuseViewBean_005f0, _jspx_page_context))
              return;
            out.write('\n');
            int evalDoAfterBody = _jspx_th_jato_005fuseViewBean_005f0.doAfterBody();
            currentContainerView = (com.iplanet.jato.view.ContainerView) _jspx_page_context.findAttribute("currentContainerView");
            currentTiledView = (com.iplanet.jato.view.TiledView) _jspx_page_context.findAttribute("currentTiledView");
            currentTreeView = (com.iplanet.jato.view.TreeView) _jspx_page_context.findAttribute("currentTreeView");
            viewBean = (com.sun.identity.console.policy.PolicyNormalAddViewBean) _jspx_page_context.findAttribute("viewBean");
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_jato_005fuseViewBean_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fjato_005fuseViewBean_0026_005ffireChildDisplayEvents_005fclassName.reuse(_jspx_th_jato_005fuseViewBean_005f0);
        _jspx_th_jato_005fuseViewBean_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_jato_005fuseViewBean_005f0, _jsp_getInstanceManager(), _jspx_th_jato_005fuseViewBean_005f0_reused);
      }
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_cc_005fheader_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_jato_005fuseViewBean_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cc:header
    org.forgerock.openam.console.ui.taglib.header.CCHtmlHeaderTag _jspx_th_cc_005fheader_005f0 = (org.forgerock.openam.console.ui.taglib.header.CCHtmlHeaderTag) _005fjspx_005ftagPool_005fcc_005fheader_0026_005fpageTitle_005fname_005ffireDisplayEvents_005fcopyrightYear_005fbundleID.get(org.forgerock.openam.console.ui.taglib.header.CCHtmlHeaderTag.class);
    boolean _jspx_th_cc_005fheader_005f0_reused = false;
    try {
      _jspx_th_cc_005fheader_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cc_005fheader_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jato_005fuseViewBean_005f0);
      // /console/policy/PolicyNormalAdd.jsp(41,0) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fheader_005f0.setName("hdrCommon");
      // /console/policy/PolicyNormalAdd.jsp(41,0) name = pageTitle type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fheader_005f0.setPageTitle("webconsole.title");
      // /console/policy/PolicyNormalAdd.jsp(41,0) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fheader_005f0.setBundleID("amConsole");
      // /console/policy/PolicyNormalAdd.jsp(41,0) name = copyrightYear type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fheader_005f0.setCopyrightYear("2004");
      // /console/policy/PolicyNormalAdd.jsp(41,0) name = fireDisplayEvents type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fheader_005f0.setFireDisplayEvents("true");
      int _jspx_eval_cc_005fheader_005f0 = _jspx_th_cc_005fheader_005f0.doStartTag();
      if (_jspx_eval_cc_005fheader_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_cc_005fheader_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_cc_005fheader_005f0);
        }
        do {
          out.write("\n");
          out.write("\n");
          out.write("<script language=\"javascript\" src=\"../console/js/am.js\"></script>\n");
          out.write("<script language=\"javascript\">\n");
          out.write("    function toggleButtonState(tblName, counterName, btn, trigger) {\n");
          out.write("\ttoggleTblButtonState('PolicyNormalAdd', 'PolicyNormalAdd.' + tblName,\n");
          out.write("\t    counterName, 'PolicyNormalAdd.' + btn, trigger);\n");
          out.write("    }\n");
          out.write("</script>\n");
          out.write("\n");
          if (_jspx_meth_cc_005fform_005f0(_jspx_th_cc_005fheader_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_cc_005fheader_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_cc_005fheader_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_cc_005fheader_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcc_005fheader_0026_005fpageTitle_005fname_005ffireDisplayEvents_005fcopyrightYear_005fbundleID.reuse(_jspx_th_cc_005fheader_005f0);
      _jspx_th_cc_005fheader_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005fheader_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005fheader_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cc_005fform_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_cc_005fheader_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cc:form
    org.forgerock.openam.console.ui.taglib.AutoCCFormTag _jspx_th_cc_005fform_005f0 = (org.forgerock.openam.console.ui.taglib.AutoCCFormTag) _005fjspx_005ftagPool_005fcc_005fform_0026_005fname_005fmethod_005fdefaultCommandChild.get(org.forgerock.openam.console.ui.taglib.AutoCCFormTag.class);
    boolean _jspx_th_cc_005fform_005f0_reused = false;
    try {
      _jspx_th_cc_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cc_005fform_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cc_005fheader_005f0);
      // /console/policy/PolicyNormalAdd.jsp(51,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fform_005f0.setName("PolicyNormalAdd");
      // /console/policy/PolicyNormalAdd.jsp(51,0) name = method type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fform_005f0.setMethod("post");
      // /console/policy/PolicyNormalAdd.jsp(51,0) name = defaultCommandChild type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fform_005f0.setDefaultCommandChild("/button1");
      int _jspx_eval_cc_005fform_005f0 = _jspx_th_cc_005fform_005f0.doStartTag();
      if (_jspx_eval_cc_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_cc_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_cc_005fform_005f0);
        }
        do {
          out.write("\n");
          out.write("<script language=\"javascript\">\n");
          out.write("    function confirmLogout() {\n");
          out.write("        return confirm(\"");
          if (_jspx_meth_cc_005ftext_005f0(_jspx_th_cc_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\");\n");
          out.write("    }\n");
          out.write("</script>\n");
          if (_jspx_meth_cc_005fprimarymasthead_005f0(_jspx_th_cc_005fform_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          if (_jspx_meth_cc_005fbreadcrumbs_005f0(_jspx_th_cc_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\n");
          out.write("<table border=\"0\" cellpadding=\"10\" cellspacing=\"0\" width=\"100%\">\n");
          out.write("    <tr>\n");
          out.write("\t<td>\n");
          out.write("\t");
          if (_jspx_meth_cc_005falertinline_005f0(_jspx_th_cc_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t</td>\n");
          out.write("    </tr>\n");
          out.write("</table>\n");
          out.write("\n");
          out.write('\n');
          if (_jspx_meth_cc_005fpagetitle_005f0(_jspx_th_cc_005fform_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('\n');
          if (_jspx_meth_cc_005fpropertysheet_005f0(_jspx_th_cc_005fform_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_cc_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_cc_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_cc_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcc_005fform_0026_005fname_005fmethod_005fdefaultCommandChild.reuse(_jspx_th_cc_005fform_005f0);
      _jspx_th_cc_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cc_005ftext_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_cc_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cc:text
    com.sun.web.ui.taglib.html.CCStaticTextFieldTag _jspx_th_cc_005ftext_005f0 = (com.sun.web.ui.taglib.html.CCStaticTextFieldTag) _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fdefaultValue_005fbundleID_005fnobody.get(com.sun.web.ui.taglib.html.CCStaticTextFieldTag.class);
    boolean _jspx_th_cc_005ftext_005f0_reused = false;
    try {
      _jspx_th_cc_005ftext_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cc_005ftext_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cc_005fform_005f0);
      // /console/policy/PolicyNormalAdd.jsp(54,24) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f0.setName("txtLogout");
      // /console/policy/PolicyNormalAdd.jsp(54,24) name = defaultValue type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f0.setDefaultValue("masthead.logoutMessage");
      // /console/policy/PolicyNormalAdd.jsp(54,24) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005ftext_005f0.setBundleID("amConsole");
      int _jspx_eval_cc_005ftext_005f0 = _jspx_th_cc_005ftext_005f0.doStartTag();
      if (_jspx_th_cc_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcc_005ftext_0026_005fname_005fdefaultValue_005fbundleID_005fnobody.reuse(_jspx_th_cc_005ftext_005f0);
      _jspx_th_cc_005ftext_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005ftext_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005ftext_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cc_005fprimarymasthead_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_cc_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cc:primarymasthead
    org.forgerock.openam.console.ui.taglib.masthead.CCPrimaryMastheadTag _jspx_th_cc_005fprimarymasthead_005f0 = (org.forgerock.openam.console.ui.taglib.masthead.CCPrimaryMastheadTag) _005fjspx_005ftagPool_005fcc_005fprimarymasthead_0026_005fname_005flogoutOnClick_005fbundleID_005fnobody.get(org.forgerock.openam.console.ui.taglib.masthead.CCPrimaryMastheadTag.class);
    boolean _jspx_th_cc_005fprimarymasthead_005f0_reused = false;
    try {
      _jspx_th_cc_005fprimarymasthead_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cc_005fprimarymasthead_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cc_005fform_005f0);
      // /console/policy/PolicyNormalAdd.jsp(57,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fprimarymasthead_005f0.setName("mhCommon");
      // /console/policy/PolicyNormalAdd.jsp(57,0) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fprimarymasthead_005f0.setBundleID("amConsole");
      // /console/policy/PolicyNormalAdd.jsp(57,0) name = logoutOnClick type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fprimarymasthead_005f0.setLogoutOnClick("return confirmLogout();");
      int _jspx_eval_cc_005fprimarymasthead_005f0 = _jspx_th_cc_005fprimarymasthead_005f0.doStartTag();
      if (_jspx_th_cc_005fprimarymasthead_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcc_005fprimarymasthead_0026_005fname_005flogoutOnClick_005fbundleID_005fnobody.reuse(_jspx_th_cc_005fprimarymasthead_005f0);
      _jspx_th_cc_005fprimarymasthead_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005fprimarymasthead_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005fprimarymasthead_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cc_005fbreadcrumbs_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_cc_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cc:breadcrumbs
    com.sun.web.ui.taglib.breadcrumb.CCBreadCrumbsTag _jspx_th_cc_005fbreadcrumbs_005f0 = (com.sun.web.ui.taglib.breadcrumb.CCBreadCrumbsTag) _005fjspx_005ftagPool_005fcc_005fbreadcrumbs_0026_005fname_005fbundleID_005fnobody.get(com.sun.web.ui.taglib.breadcrumb.CCBreadCrumbsTag.class);
    boolean _jspx_th_cc_005fbreadcrumbs_005f0_reused = false;
    try {
      _jspx_th_cc_005fbreadcrumbs_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cc_005fbreadcrumbs_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cc_005fform_005f0);
      // /console/policy/PolicyNormalAdd.jsp(58,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fbreadcrumbs_005f0.setName("breadCrumb");
      // /console/policy/PolicyNormalAdd.jsp(58,0) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fbreadcrumbs_005f0.setBundleID("amConsole");
      int _jspx_eval_cc_005fbreadcrumbs_005f0 = _jspx_th_cc_005fbreadcrumbs_005f0.doStartTag();
      if (_jspx_th_cc_005fbreadcrumbs_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcc_005fbreadcrumbs_0026_005fname_005fbundleID_005fnobody.reuse(_jspx_th_cc_005fbreadcrumbs_005f0);
      _jspx_th_cc_005fbreadcrumbs_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005fbreadcrumbs_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005fbreadcrumbs_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cc_005falertinline_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_cc_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cc:alertinline
    com.sun.web.ui.taglib.alert.CCAlertInlineTag _jspx_th_cc_005falertinline_005f0 = (com.sun.web.ui.taglib.alert.CCAlertInlineTag) _005fjspx_005ftagPool_005fcc_005falertinline_0026_005fname_005fbundleID_005fnobody.get(com.sun.web.ui.taglib.alert.CCAlertInlineTag.class);
    boolean _jspx_th_cc_005falertinline_005f0_reused = false;
    try {
      _jspx_th_cc_005falertinline_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cc_005falertinline_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cc_005fform_005f0);
      // /console/policy/PolicyNormalAdd.jsp(63,1) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005falertinline_005f0.setName("ialertCommon");
      // /console/policy/PolicyNormalAdd.jsp(63,1) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005falertinline_005f0.setBundleID("amConsole");
      int _jspx_eval_cc_005falertinline_005f0 = _jspx_th_cc_005falertinline_005f0.doStartTag();
      if (_jspx_th_cc_005falertinline_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcc_005falertinline_0026_005fname_005fbundleID_005fnobody.reuse(_jspx_th_cc_005falertinline_005f0);
      _jspx_th_cc_005falertinline_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005falertinline_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005falertinline_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cc_005fpagetitle_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_cc_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cc:pagetitle
    com.sun.web.ui.taglib.pagetitle.CCPageTitleTag _jspx_th_cc_005fpagetitle_005f0 = (com.sun.web.ui.taglib.pagetitle.CCPageTitleTag) _005fjspx_005ftagPool_005fcc_005fpagetitle_0026_005fviewMenuLabel_005fshowPageTitleSeparator_005fshowPageButtonsTop_005fshowPageButtonsBottom_005fpageTitleText_005fpageTitleHelpMessage_005fname_005fbundleID_005fnobody.get(com.sun.web.ui.taglib.pagetitle.CCPageTitleTag.class);
    boolean _jspx_th_cc_005fpagetitle_005f0_reused = false;
    try {
      _jspx_th_cc_005fpagetitle_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cc_005fpagetitle_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cc_005fform_005f0);
      // /console/policy/PolicyNormalAdd.jsp(69,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpagetitle_005f0.setName("pgtitleTwoBtns");
      // /console/policy/PolicyNormalAdd.jsp(69,0) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpagetitle_005f0.setBundleID("amConsole");
      // /console/policy/PolicyNormalAdd.jsp(69,0) name = pageTitleText type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpagetitle_005f0.setPageTitleText("page.title.policy.create");
      // /console/policy/PolicyNormalAdd.jsp(69,0) name = showPageTitleSeparator type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpagetitle_005f0.setShowPageTitleSeparator("true");
      // /console/policy/PolicyNormalAdd.jsp(69,0) name = viewMenuLabel type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpagetitle_005f0.setViewMenuLabel("");
      // /console/policy/PolicyNormalAdd.jsp(69,0) name = pageTitleHelpMessage type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpagetitle_005f0.setPageTitleHelpMessage("");
      // /console/policy/PolicyNormalAdd.jsp(69,0) name = showPageButtonsTop type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpagetitle_005f0.setShowPageButtonsTop("true");
      // /console/policy/PolicyNormalAdd.jsp(69,0) name = showPageButtonsBottom type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpagetitle_005f0.setShowPageButtonsBottom("false");
      int _jspx_eval_cc_005fpagetitle_005f0 = _jspx_th_cc_005fpagetitle_005f0.doStartTag();
      if (_jspx_th_cc_005fpagetitle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcc_005fpagetitle_0026_005fviewMenuLabel_005fshowPageTitleSeparator_005fshowPageButtonsTop_005fshowPageButtonsBottom_005fpageTitleText_005fpageTitleHelpMessage_005fname_005fbundleID_005fnobody.reuse(_jspx_th_cc_005fpagetitle_005f0);
      _jspx_th_cc_005fpagetitle_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005fpagetitle_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005fpagetitle_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_cc_005fpropertysheet_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_cc_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cc:propertysheet
    org.forgerock.openam.console.ui.taglib.propertysheet.CCPropertySheetTag _jspx_th_cc_005fpropertysheet_005f0 = (org.forgerock.openam.console.ui.taglib.propertysheet.CCPropertySheetTag) _005fjspx_005ftagPool_005fcc_005fpropertysheet_0026_005fshowJumpLinks_005fname_005fbundleID_005fnobody.get(org.forgerock.openam.console.ui.taglib.propertysheet.CCPropertySheetTag.class);
    boolean _jspx_th_cc_005fpropertysheet_005f0_reused = false;
    try {
      _jspx_th_cc_005fpropertysheet_005f0.setPageContext(_jspx_page_context);
      _jspx_th_cc_005fpropertysheet_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cc_005fform_005f0);
      // /console/policy/PolicyNormalAdd.jsp(71,0) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpropertysheet_005f0.setName("propertyAttributes");
      // /console/policy/PolicyNormalAdd.jsp(71,0) name = bundleID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpropertysheet_005f0.setBundleID("amConsole");
      // /console/policy/PolicyNormalAdd.jsp(71,0) name = showJumpLinks type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cc_005fpropertysheet_005f0.setShowJumpLinks("true");
      int _jspx_eval_cc_005fpropertysheet_005f0 = _jspx_th_cc_005fpropertysheet_005f0.doStartTag();
      if (_jspx_th_cc_005fpropertysheet_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcc_005fpropertysheet_0026_005fshowJumpLinks_005fname_005fbundleID_005fnobody.reuse(_jspx_th_cc_005fpropertysheet_005f0);
      _jspx_th_cc_005fpropertysheet_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_cc_005fpropertysheet_005f0, _jsp_getInstanceManager(), _jspx_th_cc_005fpropertysheet_005f0_reused);
    }
    return false;
  }
}
